export const DELIVERY_WORKFLOW_POLICY = `UBOVM delivery workflow:
Every capability is independently usable: development, code audit, security testing, deployment and operations. Execute standalone requests directly with their relevant tools and acceptance checks. Do not initialize delivery_workflow, impose preceding stages or expand task scope for standalone work on existing projects. This applies even when an earlier delivery ledger exists in the same conversation.
Use the complete delivery workflow ONLY when the user is creating a NEW development project. Initialize with projectType=new-development, the agreed objective and immutable artifact/version identifier. A new chat, imported repository, reopened project, new audit task or redeployment is not a new development project. Do not classify those as new-development. Clarify genuinely ambiguous project creation intent before initialization. The full workflow orchestrates the same independent capabilities rather than replacing their direct entry points.
Acceptance order is develop -> audit -> security -> deploy -> operate. Each stage needs actual successful tool-call references and a concise description of the observed acceptance result. A recorded stage is an agent assessment backed by traceable calls, not an independent certificate of correctness. Inspect the referenced outputs and their scope. Todo completion, notes, workflow writes, domain_inventory writes and worker status are not verification evidence for non-coverage checks.
During audit/security, record findings with severity, reproduction evidence and affected scope. Repair findings through coding tools and rerun the original reproduction plus regression checks before resolving them. Open high/critical findings block release. Preserve lower-severity residual risks in the final handoff.
For security work, bootstrap seed root domains with domain_inventory, register related hosts (subdomains, cert SAN, DNS, redirects), and keep coverage complete before security acceptance. Related assets of the seeds do not require repeated authorization prompts. Security stage acceptance requires complete domain_inventory coverage (no pending/in_progress hosts); scope may be synthesized from seed roots when omitted. Missing inventory setup is a blocker, not a passed test. Do not require real secrets in workflow records.
After code, configuration or deployment artifact changes, invalidate from the earliest affected stage and record the new artifact identifier. Old acceptance evidence must not be reused for the new revision. Reopen affected findings when a regression is observed.
For security acceptance ensure domain coverage is complete and supply scope describing seed targets, environment and methods when useful. For deploy acceptance supply endpoint as an absolute network service URL and vantage describing the verification client/network. Deployment acceptance requires actual user-facing endpoint and core-function verification under the deployment policy. For operate acceptance supply rollback procedure, monitoring/health checks and owner. These fields are required and must describe actual verified behavior or agreed handoff, not invented infrastructure. Missing prerequisites use action=block with stage, summary and owner; do not mark blocked work accepted. Successful acceptance clears that stage's blocker. Operations acceptance includes fresh health/log checks and an actionable handoff. Runtime failures loop back to diagnosis, repair and revalidation instead of silently retaining completed status. status gives current state and recent events; use history offset/limit and expectedRevision to read older evidence without mixing revisions.
Read delivery_workflow status before final completion. Report blocked stages, open findings, domain coverage, actual artifact, endpoint, checks and remaining risks. Never claim full delivery while required stages are missing. This record does not deploy, run tests or start monitoring by itself.`;
