// Shared by planning, execution and conversational agents so delegated work
// and final completion decisions use the same deployment acceptance criteria.
export const DEPLOYMENT_VERIFICATION_POLICY = `Deployment acceptance rule (mandatory for deployment tasks):
Do not report a deployment as successful or complete until fresh tool evidence proves the deployed service is accessible and performs its intended function through the actual user-facing endpoint. Upload success, build success, a zero exit code, a running process/container, an open port, and a deploy_remote_service status of healthy are intermediate evidence, not sufficient proof of deployment success.
Before deployment, identify the intended URL/hostname, protocol, port, access scope (public or private), and a meaningful expected response. Include end-to-end accessibility verification as an explicit final plan step and completion checkpoint. Derive the endpoint from the user request or project configuration; ask for missing essential information rather than inventing an address or expected result.
For web services, request the actual deployed URL using a browser or HTTP tool from a client in the intended access scope, independently of the deployed server when possible. A localhost check on the server alone does not prove that users can access the service. Verify DNS, connection, TLS without disabling certificate verification, the final URL after redirects, the expected HTTP status, and meaningful response content. Reject unrelated landing pages, proxy error pages, stale versions, redirect loops, and unexpected login pages even if they return HTTP 200. Where a version marker or artifact identifier exists, confirm the response belongs to the new deployment. For web applications, use the available browser to load the page and exercise at least one core user flow; check that required assets and API requests succeed. For APIs, validate the response structure and expected values, not only the status code. For intentionally authenticated services, verify the expected authentication behavior and, when authorized credentials are available, the protected function; missing credentials leave functional verification incomplete.
For non-web services, use a real protocol-level request and validate a meaningful response or operation from the intended client network. TCP connection success alone is insufficient. Use bounded retries with deadlines for startup readiness; do not replace verification with a fixed sleep, true/echo commands, ignored errors, or an unchecked success flag. A health_check_command must perform a real request and return nonzero for transport errors, unexpected statuses or invalid content.
If verification fails, inspect logs and network/proxy/firewall configuration, fix issues within the authorized scope, and repeat the end-to-end check after the final change. If tools, network access, credentials or other prerequisites prevent the check, explicitly report deployment as unverified or blocked and identify the missing evidence; never label it successful. Do not change the agreed acceptance criteria just to obtain a passing result.
Final deployment reports and durable facts must include the verified endpoint, client/network vantage point, actual checks and observed results, and tool evidence references where supported. Distinguish uploaded/started from accessible/verified. Planners and coordinating agents must inspect worker verification evidence and keep the deployment goal incomplete while user-facing accessibility or required functionality remains unverified.`;
